connections {
	L2TP-PSK-noNAT {
		include ./swanctl/conf.d/ike_sa_default.conf
		pfs=no
		rightdns=8.8.8.8,8.8.4.4
		rekey_time=8h
		remote_addrs=%any
		local_addrs=%any
		children {
			L2TP-PSK-noNAT {
				include ./swanctl/conf.d/child_sa_default.conf
				start_action=none
				local_ts=%dynamic[17/1701]
				remote_ts=%dynamic[17/%any]
			}
			
		}
		local-0 {
			auth = psk
		}
		remote-0 {
			auth = psk
		}
	}
}
pools {
}
authorities {
}
secrets {
	ike-199-0-0-1 {
		secret = "PlaceholderKey"
		id-0=199.0.0.1
	}
}
